### ISSUE TITLE
inventory plots & artists to figure out projections

### ISSUE THREAD

**Issue by story645** [story645/proposal#1]
figure out which projections belong to which plots and artists

**Comment by mdogy** [comment]
The secret to getting ahead is getting started - Mark Twain

great!

-michael

Michael D. Grossberg
Associate Professor of Computer Science
Co-Director of Data Science and Data Engineering Masters Program
City College, City University of New York
NAC Building 7/311
160 Convent Avenue
New York, NY  10031

email: mgrossberg@ccny.cuny.edu <grossberg@cs.ccny.cuny.edu>
voice: 212-650-6166
fax: 212-650-6248
