### ISSUE TITLE
slides feedback

### ISSUE THREAD

**Issue by story645** [story645/proposal#20]
- [x] change out first slide image for table scatter heat image, remove words, pull constraints bullet list here. 
- [x] explain alpha and omega (or drop or move to when explaining model)
- [x] lable k0.... in fb graph
- [x] consistent example dataset that unpack
- [x] add roadmapping - swap out FB image for bullet list 
- [x] make clear coordinate system agnostic way of passing data and structures
- [ ] clean up the story arc -> use paper structure?
- [x] integrate the literature section into the story - Spivak about fiber, push Schiedigger into the artist section
- [x] apply fiber bundle to real data/ have formalism
- [ ] add timeline/gant chart
- [ ] make clearer that this is math + implementation

**Comment by tacaswell** [comment]
- talk slower
- define equiveriance before using it in a sentence
- in general be careful about jargon

- "tools tuned to DATE continuity"
- don't use general-purpose data figure when talking about networks
- never go backwards in your slides x 10
- define semiotics

- move Fiber slide a bit later, were not sure why we cared about it when it came up
  - flip these two slides
- have not really motivated monoids

- {} read to me as "set" which are not ordered so this is very confusing
  - not clear the thing we should be looking at here is the _arrows_ not the emoji

- re-order the connectivity slides


- go left-to-right in graphic continuity slide
